### ISSUE TITLE
PlaceRecognition CSV should be tolerant of leading spaces in names

### ISSUE THREAD

**Issue by pradh** [datacommonsorg/mixer#1263] opened 2023-09-12 03:24 UTC
If the name field has "sub-saharan africa, subsaharan africa", the ` ` in the 2nd name causes trouble.

It is a quick fix, but caused some diffs, so don't want to do it before release.

**Comment by hareesh-ms** [comment] 2024-05-14 08:38
Closing as the issue is fixed.

**Closed by hareesh-ms** 2024-05-14 08:38 UTC
